[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edge-tts>=7.2.8",
    "httpx>=0.28.1",
    "livekit-agents[cartesia,google]~=1.7",
    "livekit-plugins-deepgram>=1.7.0",
    "livekit-plugins-elevenlabs>=1.7.0",
    "livekit-plugins-groq>=1.7.0",
    "livekit-plugins-sarvam>=1.7.0",
    "livekit-plugins-silero>=1.7.0",
    "livekit-plugins-turn-detector>=1.7.0",
    "psutil>=7.2.2",
    "pyautogui>=0.9.54",
    "pyperclip>=1.11.0",
    "python-dotenv>=1.2.3",
    "pywin32>=312",
    "tzdata>=2026.3",
]

[dependency-groups]
dev = [
    "types-pywin32>=312.0.0.20260827",
]
