import os
from dotenv import load_dotenv

load_dotenv(".env.local")

LIVEKIT_URL = os.getenv("LIVEKIT_URL")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")

# LIVEKIT_INFERENCE_URL = os.getenv("LIVEKIT_INFERENCE_URL")
# LIVEKIT_INFERENCE_API_KEY = os.getenv("LIVEKIT_INFERENCE_API_KEY")
# LIVEKIT_INFERENCE_API_SECRET = os.getenv("LIVEKIT_INFERENCE_API_SECRET")
