SARVAM_TTS_MODEL = "bulbul:v3"
SARVAM_TTS_LANGUAGE = "hi-IN"
SARVAM_TTS_SPEAKER = "shubh"

CARTESIA_TTS_MODEL = "sonic-3"
CARTESIA_TTS_VOICE = "4877b818-c7fe-4c89-b1cf-eadf8e23da72"
CARTESIA_TTS_LANGUAGE = "hi"
CARTESIA_TTS_SPEED = 1.0
CARTESIA_TTS_VOLUME = 1.0

ELEVEN_TTS_VOICE_ID = "iP95p4xoKVk53GoZ742B"
ELEVEN_TTS_MODEL = "eleven_flash_v2_5"
ELEVEN_TTS_LANGUAGE = "hi"
ELEVEN_TTS_AUTO_MODE = True
ELEVEN_TTS_STREAMING_LATENCY = 4
ELEVEN_TTS_VOICE_STABILITY = 0.55
ELEVEN_TTS_VOICE_SIMILARITY_BOOST = 0.8
ELEVEN_TTS_VOICE_STYLE = 0.15
ELEVEN_TTS_VOICE_USE_SPEAKER_BOOST = True
ELEVEN_TTS_VOICE_SPEED = 0.95

GOOGLE_TTS_MODEL = "gemini-3.1-flash-tts-preview"
GOOGLE_TTS_VOICE = "Charon"

EDGE_TTS_VOICE = "hi-IN-MadhurNeural"
EDGE_TTS_RATE = "+12%"
EDGE_TTS_VOLUME = "+0%"
EDGE_TTS_PITCH = "-12Hz"